# Generated by Django 4.0.5 on 2022-06-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_profile_user_profile_victor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='victor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
