# Generated by Django 4.0.5 on 2022-07-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_created_shopcart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='victor',
            new_name='user',
        ),
    ]
